name       : libappindicator
version    : 12.10.0
release    : 4
source     :
    - https://launchpad.net/libappindicator/12.10/12.10.0/+download/libappindicator-12.10.0.tar.gz : d5907c1f98084acf28fd19593cb70672caa0ca1cf82d747ba6f4830d4cc3b49f
license    :
    - GPL-3.0
    - LGPL-2.1
component  : programming.library
summary    : Application Indicator Library
description: |
    Application Indicator Library
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(atk)
    - pkgconfig32(gtk+-2.0)
    - pkgconfig32(gtk+-3.0)
    - pkgconfig32(gio-unix-2.0)
    - pkgconfig32(indicator-0.4)
    - pkgconfig32(indicator3-0.4)
    - pkgconfig32(dbusmenu-gtk-0.4)
    - pkgconfig32(dbusmenu-gtk3-0.4)
    - pkgconfig32(xshmfence)
    - glibc-32bit-devel
    - libgcc-32bit
    - vala
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-Python-build-required-for-multilib-build.patch
    autoreconf -vfi
    mkdir b2
    mkdir b3
    pushd b2

    ../configure --disable-static --prefix=/usr --with-gtk=2 %CONFOPTS%
    popd
    pushd b3
    ../configure --disable-static --prefix=/usr --with-gtk=3 %CONFOPTS%
build      : |
    (pushd b2; %make)
    (pushd b3; %make)
install    : |
    (pushd b2; %make_install -j1)
    (pushd b3; %make_install -j1)
