name       : libappindicator
version    : 12.10.1
release    : 5
source     :
    - https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/libappindicator/12.10.1+20.04.20200408.1-0ubuntu1/libappindicator_12.10.1+20.04.20200408.1.orig.tar.gz : c9f3be3b8b23a459162b258712db29d345bde8fe9bfefe235cacd6db07599b06
license    :
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Application Indicator Library
description: |
    Application Indicator Library
builddeps  :
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(dbusmenu-gtk-0.4)
    - pkgconfig32(dbusmenu-gtk3-0.4)
    - pkgconfig32(libgcrypt)
    - pkgconfig32(xshmfence)
    - gnome-common
    - vala
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-Strip-out-docs.patch
    autoreconf -vfi
    mkdir b2
    mkdir b3
    pushd b2
    ../configure --disable-static --disable-tests --prefix=/usr --with-gtk=2 %CONFOPTS%
    popd

    pushd b3
    ../configure --disable-static --disable-tests --prefix=/usr --with-gtk=3 %CONFOPTS%
build      : |
    %make -C b2
    %make -C b3
install    : |
    %make_install -j1 -C b2
    %make_install -j1 -C b3
